// SPDX-License-Identifier: MPL-2.0

import * as vscode from 'vscode';

import { MIRROR_DIR, renderInputDeclarations, scanJsBlocks, type JsInputBinding } from './jsBlocks';

const SHIPPED_GLOBALS = ['types', 'js65-globals.d.ts'];

const HEADER = `// Generated by the js65 extension for editing .jsbegin blocks.
`;

export interface JsGlobals {
	/** The `.d.ts` holding every name a `.jsbegin` block can use. */
	readonly uri: vscode.Uri;
	/** Rewrites it if the open `.jsinput` set has changed since last time. */
	refresh(): Promise<void>;
}

export function registerJsGlobals(
	context: vscode.ExtensionContext, log: vscode.LogOutputChannel): JsGlobals | undefined {
	const storage = context.storageUri ?? context.globalStorageUri;
	if (!storage) return undefined;

	const shipped = vscode.Uri.joinPath(context.extensionUri, ...SHIPPED_GLOBALS);
	// Alongside the mirrors, so the project they share picks these up as one of
	// its own files rather than through a reference that can fail silently.
	const dir = vscode.Uri.joinPath(storage, MIRROR_DIR);
	const target = vscode.Uri.joinPath(dir, 'js65-blocks.d.ts');
	let published: string | undefined;
	// Serialized, so awaiting a refresh really does mean the file is on disk:
	// a second caller must not skip out early on a write still in flight.
	let inFlight: Promise<void> = Promise.resolve();

	const rewrite = async (): Promise<void> => {
		const text = await render(shipped, collectInputs(), log);
		if (text === published) return;
		published = text;
		try {
			await vscode.workspace.fs.createDirectory(dir);
			await vscode.workspace.fs.writeFile(target, Buffer.from(text, 'utf8'));
		} catch {
			// Losing completions inside a block is not worth interrupting the
			// user over, and the next edit tries again.
			published = undefined;
		}
	};

	const refresh = (): Promise<void> => (inFlight = inFlight.then(rewrite));

	context.subscriptions.push(
		vscode.workspace.onDidOpenTextDocument(doc => { if (isJs65(doc)) void refresh(); }),
		vscode.workspace.onDidCloseTextDocument(doc => { if (isJs65(doc)) void refresh(); }),
		// `.jsinput` lines are edited like any other, so track the live text
		// rather than waiting for a save.
		vscode.workspace.onDidChangeTextDocument(e => { if (isJs65(e.document)) void refresh(); }),
	);
	void refresh();
	return {uri: target, refresh};
}

function isJs65(doc: vscode.TextDocument): boolean {
	return doc.languageId === 'js65';
}

function collectInputs(): JsInputBinding[] {
	const byName = new Map<string, JsInputBinding>();
	for (const doc of vscode.workspace.textDocuments) {
		if (!isJs65(doc)) continue;
		for (const input of scanJsBlocks(doc.getText()).inputs) {
			if (!byName.has(input.name)) byName.set(input.name, input);
		}
	}
	return [...byName.values()];
}

/**
 * Builds the one declaration file a mirror references.
 *
 * The shipped declarations are copied in rather than pulled in with a second
 * `/// <reference>`: when that file is missing - it is generated by
 * `bun run build:jsglobals` and is not in the repository - a reference to it
 * fails silently, and the only symptom is that `a` and `defines` quietly stop
 * completing. Reading it here turns that into something the log can report.
 */
async function render(shipped: vscode.Uri, inputs: readonly JsInputBinding[],
	log: vscode.LogOutputChannel): Promise<string> {
	let globals = '';
	try {
		globals = new TextDecoder().decode(await vscode.workspace.fs.readFile(shipped));
	} catch {
		log.error(`Cannot read ${shipped.fsPath}, so \`a\` and \`defines\` will not ` +
			'complete inside .jsbegin blocks. Run `bun run build:jsglobals` in lsp/client.');
	}
	const declarations = renderInputDeclarations(inputs);
	return `${HEADER}${globals}${declarations ? `\n${declarations}\n` : ''}`;
}
