// SPDX-License-Identifier: MPL-2.0

import * as vscode from 'vscode';

import { renderInputDeclarations, scanJsBlocks, type JsInputBinding } from './jsBlocks';

const SHIPPED_GLOBALS = ['types', 'js65-globals.d.ts'];

const HEADER = `// Generated by the js65 extension for editing .jsbegin blocks.
`;

export function registerJsGlobals(context: vscode.ExtensionContext): void {
	const storage = context.storageUri ?? context.globalStorageUri;
	if (!storage) return;

	const shipped = vscode.Uri.joinPath(context.extensionUri, ...SHIPPED_GLOBALS);
	const target = vscode.Uri.joinPath(storage, 'js65-blocks.d.ts');
	let published: string | undefined;

	const refresh = async (): Promise<void> => {
		const inputs = collectInputs();
		const text = render(shipped, inputs);
		if (text === published) return;
		published = text;
		try {
			await vscode.workspace.fs.createDirectory(storage);
			await vscode.workspace.fs.writeFile(target, Buffer.from(text, 'utf8'));
		} catch {
			// Losing completions inside a block is not worth interrupting the
			// user over, and the next edit tries again.
			published = undefined;
		}
	};

	context.subscriptions.push(
		vscode.workspace.onDidOpenTextDocument(doc => { if (isJs65(doc)) void refresh(); }),
		vscode.workspace.onDidCloseTextDocument(doc => { if (isJs65(doc)) void refresh(); }),
		// `.jsinput` lines are edited like any other, so track the live text
		// rather than waiting for a save.
		vscode.workspace.onDidChangeTextDocument(e => { if (isJs65(e.document)) void refresh(); }),
	);
	void refresh();
}

function isJs65(doc: vscode.TextDocument): boolean {
	return doc.languageId === 'js65';
}

function collectInputs(): JsInputBinding[] {
	const byName = new Map<string, JsInputBinding>();
	for (const doc of vscode.workspace.textDocuments) {
		if (!isJs65(doc)) continue;
		for (const input of scanJsBlocks(doc.getText()).inputs) {
			if (!byName.has(input.name)) byName.set(input.name, input);
		}
	}
	return [...byName.values()];
}

function render(shipped: vscode.Uri, inputs: readonly JsInputBinding[]): string {
	const reference = `/// <reference path="${shipped.fsPath.replace(/\\/g, '/')}" />\n`;
	const declarations = renderInputDeclarations(inputs);
	return `${HEADER}${reference}${declarations ? `\n${declarations}\n` : ''}`;
}
