// SPDX-License-Identifier: MPL-2.0

// Bundles each src/jsmodule/<name>/entry.ts into <name>.generated.ts.

import { readdirSync, renameSync, writeFileSync } from 'fs';
import { join } from 'path';

const ROOT = join(import.meta.dirname, '.');
const MODULE_DIR = join(ROOT, 'src', 'jsmodule');

// compile flag for removing sourceMaps from the modules since thats quite space intensive
const WITH_MAPS = !process.argv.includes('--no-maps');

function moduleNames(): string[] {
  return readdirSync(MODULE_DIR, { withFileTypes: true })
    .filter(e => e.isDirectory())
    .map(e => e.name)
    .sort();
}

/** Only the fields the runtime consumer reads, to keep the payload down. */
interface TrimmedMap {
  version: number;
  sources: string[];
  sourcesContent?: (string | null)[];
  mappings: string;
}

/**
 * Rewrites `src/jsmodule/bmp/vendor/binary.ts` to `vendor/binary.ts`, so a
 * frame reads as a path inside the module rather than inside this repo.
 */
function trimMap(name: string, json: string): TrimmedMap {
  const raw = JSON.parse(json) as TrimmedMap;
  const prefix = `src/jsmodule/${name}/`;
  return {
    version: raw.version,
    sources: raw.sources.map(s => s.startsWith(prefix) ? s.substring(prefix.length) : s),
    sourcesContent: raw.sourcesContent,
    mappings: raw.mappings,
  };
}

async function bundle(name: string): Promise<{code: string, map?: string}> {
  const built = await Bun.build({
    entrypoints: [join(MODULE_DIR, name, 'entry.ts')],
    format: 'iife',
    target: 'browser',
    minify: true,
    sourcemap: WITH_MAPS ? 'external' : 'none',
  });
  if (!built.success) {
    throw new Error(`bundling ${name} failed:\n${built.logs.join('\n')}`);
  }
  const chunks = built.outputs.filter(o => o.kind !== 'sourcemap');
  if (chunks.length !== 1) {
    throw new Error(`bundling ${name} produced ${chunks.length} chunks, expected 1`);
  }
  const code = (await chunks[0].text()).replace(/\s+$/, '').replace(/;$/, '');
  if (/\b(?:import|require)\s*\(/.test(code)) {
    throw new Error(`bundle for ${name} still has a dynamic import or require`);
  }
  const mapOutput = built.outputs.find(o => o.kind === 'sourcemap');
  if (WITH_MAPS && !mapOutput) {
    throw new Error(`bundling ${name} produced no source map`);
  }
  const map = mapOutput
      ? JSON.stringify(trimMap(name, await mapOutput.text())) : undefined;
  return {code, map};
}

const HEADER = `\
// SPDX-License-Identifier: MPL-2.0

// This file is auto generated by gen-jsmodules.ts. Do not edit.
`;

function generated(name: string, code: string): string {
  // The bundle starts on its own line, so a source map position is the module's
  // line plus one with no column arithmetic against the `const` prefix.
  return `${HEADER}export const text = ${JSON.stringify(`const ${name} =\n${code};`)};\n`;
}

function generatedMap(map: string): string {
  return `${HEADER}export const map = ${JSON.stringify(map)};\n`;
}

function generatedIndex(withMaps: readonly string[]): string {
  const imports = withMaps
      .map(n => `import * as ${n} from './${n}.map.generated.ts';`).join('\n');
  const entries = withMaps.map(n => `    ['${n}', ${n}.map],`).join('\n');
  return `${HEADER}${imports}${imports ? '\n\n' : ''}\
/** Source maps for the bundled modules, empty in a build that ships none. */
export const JS_MODULE_MAPS: Map<string, string> = new Map(
  [
${entries}
  ]
);
`;
}

function writeAtomic(path: string, content: string) {
  const tmp = `${path}.tmp${process.pid}`;
  writeFileSync(tmp, content);
  renameSync(tmp, path);
}

const mapped: string[] = [];
for (const name of moduleNames()) {
  const {code, map} = await bundle(name);
  writeAtomic(join(MODULE_DIR, `${name}.generated.ts`), generated(name, code));
  if (map) {
    writeAtomic(join(MODULE_DIR, `${name}.map.generated.ts`), generatedMap(map));
    mapped.push(name);
  }
}
writeAtomic(join(MODULE_DIR, 'maps.generated.ts'), generatedIndex(mapped));
