// SPDX-License-Identifier: MPL-2.0

// Bundles each src/jsmodule/<name>/entry.ts into <name>.generated.ts.

import { readdirSync, renameSync, writeFileSync } from 'fs';
import { join } from 'path';

const ROOT = join(import.meta.dirname, '.');
const MODULE_DIR = join(ROOT, 'src', 'jsmodule');

function moduleNames(): string[] {
  return readdirSync(MODULE_DIR, { withFileTypes: true })
    .filter(e => e.isDirectory())
    .map(e => e.name)
    .sort();
}

async function bundle(name: string): Promise<string> {
  const built = await Bun.build({
    entrypoints: [join(MODULE_DIR, name, 'entry.ts')],
    format: 'iife',
    target: 'browser',
    minify: true,
  });
  if (!built.success) {
    throw new Error(`bundling ${name} failed:\n${built.logs.join('\n')}`);
  }
  if (built.outputs.length !== 1) {
    throw new Error(`bundling ${name} produced ${built.outputs.length} chunks, expected 1`);
  }
  const code = (await built.outputs[0].text()).trim().replace(/;$/, '');
  if (/\b(?:import|require)\s*\(/.test(code)) {
    throw new Error(`bundle for ${name} still has a dynamic import or require`);
  }
  return code;
}

function generated(name: string, code: string): string {
  return `\
// SPDX-License-Identifier: MPL-2.0

// This file is auto generated by tools/build-jsmodules.ts. Do not edit.
export const text = ${JSON.stringify(`const ${name} = ${code};`)};
`;
}

function writeAtomic(path: string, content: string) {
  const tmp = `${path}.tmp${process.pid}`;
  writeFileSync(tmp, content);
  renameSync(tmp, path);
}

for (const name of moduleNames()) {
  const content = generated(name, await bundle(name));
  writeAtomic(join(MODULE_DIR, `${name}.generated.ts`), content);
  // process.stderr.write(`jsmodule ${name}: ${content.length} bytes\n`);
}
