// SPDX-License-Identifier: MPL-2.0

/**
 * Emits the global declarations that are available inside `.jsbegin` and `.jspostbegin` blocks.
 */

import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..');
const SOURCE = join(REPO, 'src', 'builder.ts');
const LINKER = join(REPO, 'src', 'linker.ts');
const OUT = join(HERE, 'client', 'types', 'js65-globals.d.ts');

interface Method {
  name: string;
  params: string;
  doc?: string;
}

/** Pulls the label types `labelMap` holds out of linker.ts, minus their `export`. */
function labelTypes(source: string): string {
  const type = /^export (type MesenLabelFormatType = [^;]*;)$/m.exec(source);
  const iface = /^export (interface MesenLabelFormat \{[^}]*\})$/m.exec(source);
  if (!type || !iface) throw new Error('Could not find MesenLabelFormat in linker.ts');
  return `declare ${type[1]}\n\ndeclare ${iface[1]}`;
}

/** Pulls the `export class AsmModule { ... }` body out of the source text. */
function classBody(source: string): string {
  const start = source.indexOf('export class AsmModule');
  if (start < 0) throw new Error('Could not find AsmModule in builder.ts');
  const open = source.indexOf('{', start);
  let depth = 0;
  for (let i = open; i < source.length; i++) {
    if (source[i] === '{') depth++;
    else if (source[i] === '}' && --depth === 0) return source.substring(open + 1, i);
  }
  throw new Error('Unterminated AsmModule class body');
}

// Find just the public methods
const RE_METHOD = /^ {2}([a-zA-Z_$][\w$]*)\(([^)]*)\)\s*:\s*this\s*\{/;
const RE_DOC_ONELINE = /^ {2}\/\*\* (.*?) \*\/$/;

function parse(body: string): Method[] {
  const lines = body.split('\n');
  const methods: Method[] = [];
  let doc: string[] = [];
  for (const line of lines) {
    const one = RE_DOC_ONELINE.exec(line);
    if (one) { doc = [one[1]]; continue; }
    if (/^ {2}\/\*\*/.test(line)) { doc = [line.replace(/^ {2}\/\*\*\s?/, '').trim()]; continue; }
    if (doc.length && /^ {3}\*/.test(line)) {
      doc.push(line.replace(/^ {3}\*\/?\s?/, '').replace(/\s*\*\/$/, '').trim());
      continue;
    }
    const m = RE_METHOD.exec(line);
    if (m) {
      methods.push({name: m[1], params: m[2].trim(),
                    doc: doc.filter(Boolean).join(' ') || undefined});
    }
    doc = [];
  }
  if (!methods.length) throw new Error('No fluent AsmModule methods found');
  return methods;
}

function render(methods: Method[], labels: string): string {
  const decls = methods.map(m => {
    const doc = m.doc ? `  /** ${m.doc} */\n` : '';
    return `${doc}  ${m.name}(${m.params}): AsmModule;`;
  }).join('\n\n');

  return `// SPDX-License-Identifier: MPL-2.0
// Generated by lsp/gen-jsglobals.ts from src/builder.ts and src/linker.ts. Do not edit by hand.

declare interface Sym {
  op: 'sym';
  sym: string;
}

declare type ByteWordValue = number | Sym;
declare type ByteValue = ByteWordValue | string;

/** The fluent builder bound as \`a\` inside a \`.jsbegin\` block. */
declare interface AsmModule {
${decls}
}

/** One \`.jsinput\` file. Path is where the file was loaded from and contents are in bytes and text. */
declare interface JsInputFile {
  path: string;
  bytes: Uint8Array;
  text: string;
}

/** Emits assembly from a \`.jsbegin\` block. */
declare const a: AsmModule;

/** \`-D\` values */
declare const defines: Record<string, string | number | undefined>;

/**
 * Copy of the base ROM image or empty when there is none.
 * Writes to the base ROM are merged into the output at link time in the order that
 * the modules are passed to the linker. Can be grown by resizing the underlying
 * buffer with \`baserom.buffer.resize(n)\`.
 */
declare const baserom: Uint8Array<ArrayBuffer>;

${labels}

/**
 * \`.jspostbegin\` only. Copy of the final linked ROM, which becomes the output once
 * every block has run. Can be grown with \`rom.buffer.resize(n)\`.
 * If you are writing a \`.jsbegin\` block and want data from the original rom
 * that you are patching, see \`.baserom\` instead.
 */
declare const rom: Uint8Array<ArrayBuffer>;

/**
 * \`.jspostbegin\` only. Debug labels keyed by label name, empty unless the
 * link generates debug info.
 */
declare const labelMap: ReadonlyMap<string, MesenLabelFormat>;
`;
}

await Bun.write(OUT, render(parse(classBody(await Bun.file(SOURCE).text())),
                            labelTypes(await Bun.file(LINKER).text())));
console.log(`Wrote ${OUT}`);
