
// SPDX-License-Identifier: MPL-2.0

import { RecoverableError, type AssemblerMessage, type ErrorCollector } from './error.ts';
import type { OverwriteMode } from './module.ts';
import type { RefExtractor } from './assembler.ts';


/**
 * All of the different set of options for the Assembler/Tokenizer/Linker
 * are gathered here since the CLI can pass in feature options now,
 * and the `.feature` can change them at runtime, so we need to reference
 * these classes all over the place now.
 */

export interface TokenizerOptions {
  /**
   * When a file is included, the file path is appended to each include path and
   * loaded through the FS callbacks.
   */
  includePaths?: string[];
  /** Search path for `.incbin`. */
  binIncludePaths?: string[];
  // caseInsensitive?: boolean; // handle elsewhere?
  generateDebugInfo?: boolean;

  /** `\` escapes a newline, continuing a declaration across lines. */
  lineContinuations?: boolean;
  /** `_` is ignored inside a numeric literal, as an arbitrary separator. */
  numberSeparators?: boolean;
  /** `/* ... *\/` block comments. */
  cComments?: boolean;
}

/** Options the assembler reads. */
export interface AssemblerOptions {
  reentrantScopes?: boolean;
  overwriteMode?: OverwriteMode;
  refExtractor?: RefExtractor;
  generateDebugInfo?: boolean;
  moduleName?: string;
  tokenizerOptions?: TokenizerOptions;

  /** `[addr]` is indirect addressing, alongside `(addr)`. */
  allowBrackets?: boolean;
  /** A leading identifier is a label even without a trailing `:`. */
  labelsWithoutColons?: boolean;
  /** `*= $8000` is accepted as sugar for `.org $8000`. */
  pcAssignment?: boolean;
  /** Out-of-range values truncate instead of failing. TODO hook up to the linker */
  forceRange?: boolean;
}

/** Options the linker reads. */
export interface LinkerOptions {
  target?: string;
  /** Full text of the linker config file. */
  linkerConfig?: string;
  /** Name to report `linkerConfig` parse errors against. */
  linkerConfigName?: string;
  /** List of errors generated by the linker */
  errorCollector?: ErrorCollector;
}

export class UnknownFeatureError extends Error {}
export class UnsupportedFeatureError extends Error {}

export function applyFeature(name: string, asm: AssemblerOptions, tok: TokenizerOptions, on = true): void {
  const key = name.toLowerCase();
  switch (key) {
    case 'bracket_as_indirect': asm.allowBrackets = on; return;
    case 'labels_without_colons': asm.labelsWithoutColons = on; return;
    case 'pc_assignment': asm.pcAssignment = on; return;
    case 'force_range': asm.forceRange = on; return;
    case 'c_comments': tok.cComments = on; return;
    // ca65 defaults this off; js65 defaults it on. Turning it off works.
    case 'line_continuations': tok.lineContinuations = on; return;
    case 'underline_in_numbers': tok.numberSeparators = on; return;

    // Features js65 already applies unconditionally, so there is nothing to toggle.
    case 'at_in_identifiers':
    case 'addrsize':
    case 'string_escapes':
    case 'loose_string_term':
    case 'loose_char_term':
    case 'missing_char_term':
    case 'ubiquitous_idents':
    case 'org_per_seg': {
      const reason = UNCONDITIONAL.get(key);
      throw new RecoverableError(`Cannot change feature ${key} (${reason})`)
    }
    // 65816-only, and js65 assembles 6502 only.
    case 'long_jsr_jmp_rts':
      return;

    default: {
      const reason = UNSUPPORTED.get(key);
      if (reason) throw new UnsupportedFeatureError(`${key} (${reason})`);
      throw new UnknownFeatureError(name);
    }
  }
}

// Applies the list of features provided by the cli or library
export function applyFeatures(names: readonly string[],
                              asm: AssemblerOptions,
                              tok: TokenizerOptions): AssemblerMessage[] {
  const messages: AssemblerMessage[] = [];
  for (const name of names) {
    try {
      applyFeature(name, asm, tok);
    } catch (err) {
      if (err instanceof RecoverableError) {
        messages.push({level: 'warning', message: err.message});
      } else if (err instanceof UnknownFeatureError) {
        messages.push({level: 'error', message: `Unknown feature: ${err.message}`});
      } else if (err instanceof UnsupportedFeatureError) {
        messages.push({level: 'error', message: `Unsupported feature: ${err.message}`});
      } else {
        throw err;
      }
    }
  }
  return messages;
}

const UNCONDITIONAL = new Map<string, string>([
  ['at_in_identifiers', '`@` is always js65 cheap-local prefix'],
  ['addrsize', '`.addrsize()` is always available'],
  ['string_escapes', '`\\u`, `\\x` and `\\<char>` always honored'],
  ['loose_string_term', 'both quote styles always accepted'],
  ['loose_char_term', 'single-quoted strings are character literals'],
  ['missing_char_term', 'an unterminated string recovers, not fatal'],
  ['ubiquitous_idents', 'a macro may already shadow a mnemonic'],
  ['org_per_seg', '`.org` is already per-chunk; there is no global PC'],
]);

const UNSUPPORTED = new Map<string, string>([
  ['leading_dot_in_identifiers',
   'a leading `.` currently always starts a control statement'],
  ['dollar_in_identifiers', '`$` currently always starts a hex literal'],
  ['dollar_is_pc',
   '`$` currently always starts a hex literal; js65 spells the PC `*`'],
]);

export const FEATURE_NAMES: readonly string[] = [
  'addrsize', 'at_in_identifiers', 'bracket_as_indirect', 'c_comments',
  'dollar_in_identifiers', 'dollar_is_pc', 'force_range',
  'labels_without_colons', 'leading_dot_in_identifiers', 'line_continuations',
  'long_jsr_jmp_rts', 'loose_char_term', 'loose_string_term',
  'missing_char_term', 'org_per_seg', 'pc_assignment', 'string_escapes',
  'ubiquitous_idents', 'underline_in_numbers',
];
